# Generated by Django 2.0.6 on 2018-07-31 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carpooling', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email adress')),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='pseudo')),
                ('first_name', models.CharField(max_length=30, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='nom')),
                ('driver_license', models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')], default=False, verbose_name='permis')),
                ('trainee', models.BooleanField(choices=[(True, 'Stagiare'), (False, 'Employé')], default=False, verbose_name='statut')),
                ('car_owner', models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')], default=False, verbose_name="propriétaire d'un véhicule")),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('smoker', models.BooleanField(choices=[(True, 'Fumeur'), (False, 'Non Fumeur')], default=False, verbose_name='Fumeur')),
                ('talker', models.BooleanField(choices=[(True, 'Tres Bavard'), (False, 'Peu Bavard')], default=False, verbose_name='Bavard')),
                ('music', models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')], default=False, verbose_name='Musique')),
                ('is_active', models.BooleanField(default=True, verbose_name='Utilisateur actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('afpa_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carpooling.AfpaCenter')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='PrivateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='0', max_length=15, null=True)),
                ('afpa_number', models.CharField(default='0', max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
