# Generated by Django 2.0.5 on 2018-08-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='avatar_generique.jpg', upload_to='avatars/'),
        ),
    ]
