# Generated by Django 2.0.6 on 2018-08-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('None', 'Non communiqué'), ('Woman', 'Femme'), ('Man', 'Homme')], default='None', max_length=50),
        ),
    ]
