# Generated by Django 2.0.5 on 2018-08-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180802_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='car_owner',
            field=models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')], default=False, verbose_name="Propriétaire d'un Véhicule"),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Other gender', 'Autre'), ('Woman', 'Femme'), ('Man', 'Homme')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='talker',
            field=models.BooleanField(choices=[(True, 'Bavard'), (False, 'Peu Bavard')], default=False, verbose_name='Bavard'),
        ),
    ]
