# Generated by Django 2.0.6 on 2018-08-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180830_1208'),
        ('users', '0002_auto_20180830_1718'),
    ]

    operations = [
    ]
