# Generated by Django 2.0.6 on 2018-07-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180711_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='joined_date',
            new_name='date_joined',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='conducteur',
            field=models.BooleanField(default=False),
        ),
    ]
