# Generated by Django 2.0.6 on 2018-08-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20180831_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='trainee',
            field=models.BooleanField(choices=[(True, 'Stagiaire'), (False, 'Employé')], default=False, verbose_name='statut'),
        ),
    ]
