# Generated by Django 2.0.5 on 2018-07-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180711_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permis',
            field=models.BooleanField(default=False),
        ),
    ]
