# Generated by Django 2.0.7 on 2018-09-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180831_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_connection',
            field=models.BooleanField(default=True, verbose_name='Premiere connection'),
        ),
    ]
