# Generated by Django 2.0.5 on 2018-07-19 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_permis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='permis',
            new_name='license',
        ),
        migrations.RemoveField(
            model_name='user',
            name='conducteur',
        ),
    ]
