# Generated by Django 2.0.5 on 2018-07-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180719_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='license',
            new_name='driver_license',
        ),
    ]
