# Generated by Django 2.0.7 on 2018-07-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180723_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='car_owner',
            field=models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')], default=False, verbose_name="propriétaire d'un véhicule"),
        ),
        migrations.AlterField(
            model_name='user',
            name='trainee',
            field=models.BooleanField(choices=[(True, 'Stagiare'), (False, 'Employé')], default=False, verbose_name='stagiaire'),
        ),
    ]
