# Generated by Django 2.0.6 on 2018-07-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180723_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='car_owner',
            field=models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')], default=False, verbose_name="propriétaire d'un véhicule"),
        ),
    ]
