# Generated by Django 2.0.7 on 2018-07-26 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180725_2329'),
        ('users', '0010_auto_20180725_0906'),
    ]

    operations = [
    ]
