# Generated by Django 2.0.5 on 2018-07-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_merge_20180726_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='driver_license',
            field=models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')], default=False, verbose_name='permis'),
        ),
        migrations.AlterField(
            model_name='user',
            name='trainee',
            field=models.BooleanField(choices=[(True, 'Stagiare'), (False, 'Employé')], default=False, verbose_name='statut'),
        ),
    ]
