# Generated by Django 2.0.5 on 2018-07-30 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covoiturage', '0009_auto_20180730_1041'),
        ('users', '0012_auto_20180726_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='afpa_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='covoiturage.AfpaCenter'),
        ),
    ]
