# Generated by Django 2.0.5 on 2018-07-30 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20180730_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatedata',
            name='afpa_number',
            field=models.CharField(default='0', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='privatedata',
            name='phone_number',
            field=models.CharField(default='0', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='privatedata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
