# Generated by Django 2.0.7 on 2018-07-31 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180726_1551'),
        ('users', '0016_auto_20180730_1119'),
    ]

    operations = [
    ]
