# Generated by Django 2.0.6 on 2018-07-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180725_1355'),
        ('users', '0017_merge_20180731_0923'),
    ]

    operations = [
    ]
