# Generated by Django 2.0.5 on 2018-08-03 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('street_name', models.CharField(blank=True, max_length=200, null=True)),
                ('street_number', models.CharField(blank=True, max_length=10, null=True)),
                ('national_reference', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address_label', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
            },
        ),
        migrations.CreateModel(
            name='AfpaCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=50, verbose_name='Nom du centre')),
            ],
            options={
                'verbose_name': 'Centre AFPA',
                'verbose_name_plural': 'Centres AFPA',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='Couleur')),
                ('model', models.CharField(max_length=50, verbose_name='Modèle')),
                ('consumption', models.FloatField(blank=True, null=True, verbose_name='Consommation (en l/100km)')),
                ('fuel', models.CharField(choices=[('SP-98', 'SP-98'), ('SP-95', 'SP-95'), ('SP-95 E10', 'SP-95 E10'), ('DIESEL', 'DIESEL'), ('GPL', 'GPL'), ('ELECTRIQUE', 'ELECTRIQUE')], max_length=20, verbose_name='Type de carburant')),
                ('amount_of_free_seats', models.IntegerField(default=1, verbose_name='Nombre de places libres')),
            ],
            options={
                'verbose_name': 'Voiture',
                'verbose_name_plural': 'Voitures',
            },
        ),
        migrations.CreateModel(
            name='Car_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpooling.Car', verbose_name='Vehicule')),
            ],
        ),
    ]
