# Generated by Django 2.0.5 on 2018-08-27 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('street_name', models.CharField(blank=True, max_length=200, null=True)),
                ('street_number', models.CharField(blank=True, max_length=10, null=True)),
                ('national_reference', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address_label', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
            },
        ),
        migrations.CreateModel(
            name='AfpaCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=50, verbose_name='Nom du centre')),
            ],
            options={
                'verbose_name': 'Centre AFPA',
                'verbose_name_plural': 'Centres AFPA',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='Couleur')),
                ('model', models.CharField(max_length=50, verbose_name='Modèle')),
                ('consumption', models.FloatField(blank=True, null=True, verbose_name='Consommation (en l/100km)')),
                ('fuel', models.CharField(choices=[('SP-98', 'SP-98'), ('SP-95', 'SP-95'), ('SP-95 E10', 'SP-95 E10'), ('DIESEL', 'DIESEL'), ('GPL', 'GPL'), ('ELECTRIQUE', 'ELECTRIQUE')], max_length=20, verbose_name='Type de carburant')),
                ('amount_of_free_seats', models.IntegerField(default=1, verbose_name='Nombre de places libres')),
            ],
            options={
                'verbose_name': 'Voiture',
                'verbose_name_plural': 'Voitures',
            },
        ),
        migrations.CreateModel(
            name='DefaultTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning_departure_time', models.TimeField(verbose_name='Heure de départ')),
                ('morning_arriving_time', models.TimeField(verbose_name="Heure d'arrivée")),
                ('evening_departure_time', models.TimeField(verbose_name='Heure de retour')),
                ('evening_estimated_arriving_time', models.TimeField(null=True, verbose_name='Arrivée estimée à')),
                ('estimated_trip_cost', models.IntegerField(default=0, editable=False, verbose_name='Coût du trajet estimé')),
                ('day', models.CharField(choices=[('Monday', 'Lundi'), ('Tuesday', 'Mardi'), ('Wednesday', 'Mercredi'), ('Thursday', 'Jeudi'), ('Friday', 'Vendredi')], max_length=10, verbose_name='Jour')),
            ],
            options={
                'verbose_name': 'Trajet Type',
                'verbose_name_plural': 'Trajets Type',
            },
        ),
        migrations.CreateModel(
            name='IsAStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_or_private', models.BooleanField(choices=[(True, 'Public'), (False, 'Private')], default=False, verbose_name='Public ou privé')),
            ],
            options={
                'verbose_name': 'Point de rencontre',
                'verbose_name_plural': 'Points de rencontre',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_date', models.DateTimeField(null=True, verbose_name='Date de la proposition')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Proposition validée')),
                ('meeting_point_name', models.CharField(max_length=50, verbose_name='Nom du point de rencontre')),
            ],
            options={
                'verbose_name': 'Proposition',
                'verbose_name_plural': 'Propositions',
            },
        ),
        migrations.CreateModel(
            name='Trip_Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated_proposal', models.BooleanField(default=False, verbose_name='Proposition validée')),
            ],
        ),
        migrations.CreateModel(
            name='VisibleBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpooling.MeetingPoint', verbose_name='Point de rencontre')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('defaulttrip_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='carpooling.DefaultTrip')),
                ('trip_date', models.DateField(null=True, verbose_name='Jour du trajet')),
            ],
            options={
                'verbose_name': 'Trajet Particulier',
                'verbose_name_plural': 'Trajets Particuliers',
            },
            bases=('carpooling.defaulttrip',),
        ),
    ]
