# Generated by Django 2.0.5 on 2018-08-27 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carpooling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visibleby',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='trip_passenger',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Passager'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='meeting_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpooling.MeetingPoint', verbose_name='Point de rencontre'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='meetingpoint',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpooling.Address', verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='isastep',
            name='meeting_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpooling.MeetingPoint', verbose_name='Point de rencontre'),
        ),
        migrations.AddField(
            model_name='defaulttrip',
            name='has_for_destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='carpooling.Address', verbose_name='Destination'),
        ),
        migrations.AddField(
            model_name='defaulttrip',
            name='has_for_start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start', to='carpooling.Address', verbose_name='Départ'),
        ),
        migrations.AddField(
            model_name='defaulttrip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_trips', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='afpacenter',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='carpooling.Address', verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip_passenger',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpooling.Trip', verbose_name='Trajet'),
        ),
        migrations.AddField(
            model_name='trip',
            name='passenger',
            field=models.ManyToManyField(related_name='passengers', through='carpooling.Trip_Passenger', to=settings.AUTH_USER_MODEL, verbose_name='Passager'),
        ),
        migrations.AddField(
            model_name='isastep',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpooling.Trip', verbose_name='Trajet'),
        ),
    ]
