# Generated by Django 2.0.5 on 2018-08-02 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carpooling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.AddField(
            model_name='car',
            name='users',
            field=models.ManyToManyField(through='carpooling.Car_User', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='afpacenter',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpooling.Address', verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
