# Generated by Django 2.0.5 on 2018-08-31 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0002_auto_20180827_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaulttrip',
            name='deactivate',
            field=models.BooleanField(default=False, verbose_name='désactivation'),
        ),
        migrations.AlterField(
            model_name='defaulttrip',
            name='day',
            field=models.CharField(choices=[('Monday', 'Lundi'), ('Tuesday', 'Mardi'), ('Wednesday', 'Mercredi'), ('Thursday', 'Jeudi'), ('Friday', 'Vendredi')], max_length=10, null=True, verbose_name='Jour'),
        ),
        migrations.AlterField(
            model_name='defaulttrip',
            name='evening_departure_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de retour'),
        ),
        migrations.AlterField(
            model_name='defaulttrip',
            name='has_for_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start', to='carpooling.Address', verbose_name='Départ'),
        ),
        migrations.AlterField(
            model_name='defaulttrip',
            name='morning_arriving_time',
            field=models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée"),
        ),
        migrations.AlterField(
            model_name='defaulttrip',
            name='morning_departure_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de départ'),
        ),
    ]
