# Generated by Django 2.0.5 on 2018-08-02 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0002_auto_20180802_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Adresse', 'verbose_name_plural': 'Adresses'},
        ),
    ]
