# Generated by Django 2.0.5 on 2018-08-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0003_auto_20180802_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='consumption',
            field=models.FloatField(blank=True, null=True, verbose_name='Consommation (en l/100km)'),
        ),
    ]
