# Generated by Django 2.0.6 on 2018-08-26 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carpooling', '0003_auto_20180817_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_user',
            name='car',
        ),
        migrations.RemoveField(
            model_name='car_user',
            name='user',
        ),
        migrations.RemoveField(
            model_name='car',
            name='users',
        ),
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.DeleteModel(
            name='Car_User',
        ),
    ]
