# Generated by Django 2.0.5 on 2018-08-21 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carpooling', '0003_auto_20180817_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=10, verbose_name='Nom du Jour')),
            ],
            options={
                'verbose_name': 'Jour',
                'verbose_name_plural': 'Jours',
            },
        ),
        migrations.CreateModel(
            name='DefaultTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning_departure_time', models.DateTimeField(verbose_name='Heure de départ aller')),
                ('morning_arriving_time', models.DateTimeField(verbose_name="Heure d'arrivée aller")),
                ('evening_departure_time', models.DateTimeField(verbose_name='Heure de départ retour')),
                ('evening_estimated_arriving_time', models.DateTimeField(verbose_name="Heure d'arrivée estimée retour")),
                ('estimated_trip_cost', models.IntegerField(default=0, editable=False, verbose_name='Coût du trajet estimé')),
            ],
            options={
                'verbose_name': 'Trajet Type',
                'verbose_name_plural': 'Trajets Type',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('defaulttrip_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='carpooling.DefaultTrip')),
                ('trip_date', models.DateTimeField(null=True, verbose_name='Jour du trajet')),
            ],
            options={
                'verbose_name': 'Trajet Particulier',
                'verbose_name_plural': 'Trajets Particuliers',
            },
            bases=('carpooling.defaulttrip',),
        ),
        migrations.AddField(
            model_name='defaulttrip',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpooling.Day', verbose_name='Jour'),
        ),
        migrations.AddField(
            model_name='defaulttrip',
            name='has_for_destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Destination', to='carpooling.Address', verbose_name="Adresse d'Arrivée"),
        ),
        migrations.AddField(
            model_name='defaulttrip',
            name='has_for_start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Départ', to='carpooling.Address', verbose_name='Adresse de Départ'),
        ),
        migrations.AddField(
            model_name='defaulttrip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
    ]
