# Generated by Django 2.0.5 on 2018-08-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0004_auto_20180821_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day_name',
            field=models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi')], max_length=10, verbose_name='Nom du Jour'),
        ),
    ]
