# Generated by Django 2.0.5 on 2018-09-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0004_remove_address_national_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaulttrip',
            name='is_driver',
            field=models.BooleanField(choices=[(True, 'Conducteur'), (False, 'Passager')], default=False, verbose_name='conducteur ou passager'),
        ),
    ]
