# Generated by Django 2.0.6 on 2018-08-26 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0004_auto_20180826_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afpacenter',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='carpooling.Address', verbose_name='Adresse'),
        ),
    ]
