# Generated by Django 2.0.5 on 2018-08-03 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0005_auto_20180803_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='users',
            field=models.ManyToManyField(related_name='cars', through='carpooling.Car_User', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
