# Generated by Django 2.0.5 on 2018-08-21 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0006_auto_20180821_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='day_name',
            new_name='day',
        ),
    ]
