# Generated by Django 2.0.5 on 2018-09-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0006_auto_20180913_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaulttrip',
            name='is_driver',
        ),
        migrations.AddField(
            model_name='defaulttrip',
            name='user_is_driver',
            field=models.BooleanField(default=False, verbose_name='conducteur'),
        ),
    ]
