# Generated by Django 2.0.5 on 2018-09-17 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carpooling', '0007_auto_20180913_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated_proposal', models.BooleanField(default=False, verbose_name='Proposition validée')),
                ('default_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_trip', to='carpooling.DefaultTrip', verbose_name='Trajet')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Passager')),
            ],
        ),
        migrations.RemoveField(
            model_name='isastep',
            name='meeting_point',
        ),
        migrations.RemoveField(
            model_name='isastep',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='meetingpoint',
            name='address',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='meeting_point',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trip_passenger',
            name='passenger',
        ),
        migrations.RemoveField(
            model_name='trip_passenger',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='visibleby',
            name='meeting_point',
        ),
        migrations.RemoveField(
            model_name='visibleby',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='passenger',
        ),
        migrations.DeleteModel(
            name='IsAStep',
        ),
        migrations.DeleteModel(
            name='MeetingPoint',
        ),
        migrations.DeleteModel(
            name='Proposal',
        ),
        migrations.DeleteModel(
            name='Trip_Passenger',
        ),
        migrations.DeleteModel(
            name='VisibleBy',
        ),
        migrations.AddField(
            model_name='proposition',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='carpooling.Trip', verbose_name='Trajet'),
        ),
    ]
