# Generated by Django 2.0.5 on 2018-08-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0007_auto_20180821_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='day',
            new_name='jojo',
        ),
    ]
