# Generated by Django 2.0.5 on 2018-08-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0008_auto_20180821_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='jojo',
            new_name='day_name',
        ),
    ]
