# Generated by Django 2.0.5 on 2018-09-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0008_auto_20180917_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='message',
            field=models.TextField(default='Je vous propose de covoiturer', max_length=400),
        ),
    ]
