# Generated by Django 2.0.5 on 2018-08-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0009_auto_20180821_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaulttrip',
            name='day',
            field=models.CharField(choices=[('Monday', 'Lundi'), ('Tuesday', 'Mardi'), ('Wednesday', 'Mercredi'), ('Thursday', 'Jeudi'), ('Friday', 'Vendredi')], max_length=10, verbose_name='Nom du Jour'),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
