# Generated by Django 2.0.5 on 2018-09-19 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carpooling', '0010_auto_20180919_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL, verbose_name='Conducteur'),
        ),
    ]
