# Generated by Django 2.0.5 on 2018-08-21 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carpooling', '0010_auto_20180821_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsAStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_or_private', models.BooleanField(choices=[(True, 'Public'), (False, 'Private')], default=False, verbose_name='Public ou privé')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpooling.Address', verbose_name='Adresse')),
            ],
            options={
                'verbose_name': 'Point de rencontre',
                'verbose_name_plural': 'Points de rencontre',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_date', models.DateTimeField(null=True, verbose_name='Date de la proposition')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Proposition validée')),
                ('meeting_point_name', models.CharField(max_length=50, verbose_name='Nom du point de rencontre')),
                ('meeting_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpooling.MeetingPoint', verbose_name='Point de rencontre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Trip_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated_proposal', models.BooleanField(default=False, verbose_name='Proposition validée')),
            ],
        ),
        migrations.CreateModel(
            name='VisibleBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpooling.MeetingPoint', verbose_name='Point de rencontre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='trip_user',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpooling.Trip', verbose_name='Trajet'),
        ),
        migrations.AddField(
            model_name='trip_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='isastep',
            name='meeting_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpooling.MeetingPoint', verbose_name='Point de rencontre'),
        ),
        migrations.AddField(
            model_name='isastep',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpooling.Trip', verbose_name='Trajet'),
        ),
    ]
