# Generated by Django 2.0.5 on 2018-08-21 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carpooling', '0012_remove_trip_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip_Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated_proposal', models.BooleanField(default=False, verbose_name='Proposition validée')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Passager')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpooling.Trip', verbose_name='Trajet')),
            ],
        ),
        migrations.RemoveField(
            model_name='trip_user',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='trip_user',
            name='user',
        ),
        migrations.DeleteModel(
            name='Trip_User',
        ),
        migrations.AddField(
            model_name='trip',
            name='passenger',
            field=models.ManyToManyField(related_name='passengers', through='carpooling.Trip_Passenger', to=settings.AUTH_USER_MODEL, verbose_name='Passager'),
        ),
    ]
