# Generated by Django 2.0.5 on 2018-08-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0013_auto_20180821_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_date',
            field=models.DateField(null=True, verbose_name='Jour du trajet'),
        ),
    ]
