# Generated by Django 2.0.5 on 2018-09-20 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0013_auto_20180919_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL, verbose_name='Conducteur'),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='passenger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passenger', to=settings.AUTH_USER_MODEL, verbose_name='Passager'),
        ),
    ]
