# Generated by Django 2.0.5 on 2018-08-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0014_auto_20180821_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'verbose_name': 'Proposition', 'verbose_name_plural': 'Propositions'},
        ),
        migrations.AlterField(
            model_name='defaulttrip',
            name='evening_departure_time',
            field=models.TimeField(verbose_name='Heure de départ retour'),
        ),
        migrations.AlterField(
            model_name='defaulttrip',
            name='evening_estimated_arriving_time',
            field=models.TimeField(verbose_name="Heure d'arrivée estimée retour"),
        ),
        migrations.AlterField(
            model_name='defaulttrip',
            name='morning_arriving_time',
            field=models.TimeField(verbose_name="Heure d'arrivée aller"),
        ),
        migrations.AlterField(
            model_name='defaulttrip',
            name='morning_departure_time',
            field=models.TimeField(verbose_name='Heure de départ aller'),
        ),
    ]
