# Generated by Django 2.0.5 on 2018-09-20 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carpooling', '0014_auto_20180920_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposition',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='passenger',
        ),
        migrations.AddField(
            model_name='proposition',
            name='first_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_user', to=settings.AUTH_USER_MODEL, verbose_name='Passager'),
        ),
        migrations.AddField(
            model_name='proposition',
            name='second_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_user', to=settings.AUTH_USER_MODEL, verbose_name='Conducteur'),
        ),
    ]
