# Generated by Django 2.0.5 on 2018-08-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0015_auto_20180822_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaulttrip',
            name='evening_estimated_arriving_time',
            field=models.TimeField(null=True, verbose_name="Heure d'arrivée estimée retour"),
        ),
    ]
