# Generated by Django 2.0.5 on 2018-09-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0016_auto_20180920_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='passenger',
            field=models.ManyToManyField(related_name='passenger', through='carpooling.Register', to='carpooling.DefaultTrip'),
        ),
    ]
