# Generated by Django 2.0.5 on 2018-08-22 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0016_auto_20180822_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaulttrip',
            name='day',
            field=models.CharField(choices=[('Monday', 'Lundi'), ('Tuesday', 'Mardi'), ('Wednesday', 'Mercredi'), ('Thursday', 'Jeudi'), ('Friday', 'Vendredi')], max_length=10, verbose_name='Jour'),
        ),
        migrations.AlterField(
            model_name='defaulttrip',
            name='evening_estimated_arriving_time',
            field=models.TimeField(null=True, verbose_name='Heure estimée retour'),
        ),
        migrations.AlterField(
            model_name='defaulttrip',
            name='has_for_destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='carpooling.Address', verbose_name="Adresse d'Arrivée"),
        ),
        migrations.AlterField(
            model_name='defaulttrip',
            name='has_for_start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart', to='carpooling.Address', verbose_name='Adresse de Départ'),
        ),
        migrations.AlterField(
            model_name='defaulttrip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_trip', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
