# Generated by Django 2.0.5 on 2018-09-20 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carpooling', '0017_auto_20180920_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposition',
            name='passenger',
        ),
        migrations.RemoveField(
            model_name='register',
            name='user_defaulttrip',
        ),
        migrations.RemoveField(
            model_name='register',
            name='user_proposition',
        ),
        migrations.AddField(
            model_name='defaulttrip',
            name='passengers',
            field=models.ManyToManyField(related_name='passenger', through='carpooling.Register', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='register',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carpooling.DefaultTrip'),
        ),
        migrations.AddField(
            model_name='register',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
