# Generated by Django 2.0.5 on 2018-08-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0017_auto_20180822_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaulttrip',
            name='day',
            field=models.CharField(blank=True, choices=[('Monday', 'Lundi'), ('Tuesday', 'Mardi'), ('Wednesday', 'Mercredi'), ('Thursday', 'Jeudi'), ('Friday', 'Vendredi')], max_length=10, verbose_name='Jour'),
        ),
    ]
