# Generated by Django 2.0.5 on 2018-08-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0018_auto_20180822_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaulttrip',
            name='day',
            field=models.CharField(choices=[('Monday', 'Lundi'), ('Tuesday', 'Mardi'), ('Wednesday', 'Mercredi'), ('Thursday', 'Jeudi'), ('Friday', 'Vendredi')], default='Monday', max_length=10, verbose_name='Jour'),
        ),
    ]
