# Generated by Django 2.0.6 on 2018-07-16 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covoiturage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='lattitude',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=25, null=True, verbose_name='lattitude'),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=25, null=True, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=50, verbose_name='Nom de la rue'),
        ),
        migrations.AlterField(
            model_name='city_zipcode',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covoiturage.City', verbose_name='Villes'),
        ),
    ]
