# Generated by Django 2.0.6 on 2018-07-16 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('covoiturage', '0002_auto_20180716_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covoiturage.Address', verbose_name='Adresse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
        migrations.RenameModel(
            old_name='City_ZipCode',
            new_name='ZipCode_City',
        ),
        migrations.AddField(
            model_name='address',
            name='users',
            field=models.ManyToManyField(through='covoiturage.Adress_User', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
