# Generated by Django 2.0.6 on 2018-07-17 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covoiturage', '0003_auto_20180716_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='zipCode',
            new_name='zip_code',
        ),
        migrations.AlterField(
            model_name='adress_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='zip_code',
            field=models.CharField(max_length=10, verbose_name='Code Postal'),
        ),
    ]
