# Generated by Django 2.0.6 on 2018-07-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covoiturage', '0004_auto_20180717_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Nom de la rue'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_complement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Complément d'adresse"),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Numéro de la rue'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(max_length=60, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='zip_code',
            field=models.CharField(max_length=15, verbose_name='Code Postal'),
        ),
    ]
