# Generated by Django 2.0.6 on 2018-07-19 15:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('covoiturage', '0005_auto_20180717_1529'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress_User',
            new_name='Address_User',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='adress_label',
            new_name='address_label',
        ),
    ]
