# Generated by Django 2.0.7 on 2018-07-25 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('covoiturage', '0005_auto_20180717_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('consumption', models.FloatField()),
                ('fuel', models.CharField(choices=[('SP-98', 'SP-98'), ('SP-95', 'SP-95'), ('SP-95 E10', 'SP-95 E10'), ('DIESEL', 'DIESEL'), ('GPL', 'GPL'), ('ELECTRIQUE', 'ELECTRIQUE')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Car_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covoiturage.Car', verbose_name='Vehicule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='users',
            field=models.ManyToManyField(through='covoiturage.Car_User', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
