# Generated by Django 2.0.6 on 2018-07-25 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covoiturage', '0006_auto_20180719_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street',
            new_name='street_name',
        ),
    ]
