# Generated by Django 2.0.7 on 2018-07-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covoiturage', '0006_auto_20180725_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='amount_of_free_seats',
            field=models.IntegerField(default=1),
        ),
    ]
