# Generated by Django 2.0.6 on 2018-07-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covoiturage', '0007_auto_20180725_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='address_user',
            name='address_label_private',
            field=models.CharField(blank=True, default='Adresse', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_label',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Libellé de l'adresse"),
        ),
    ]
