# Generated by Django 2.0.5 on 2018-07-30 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covoiturage', '0008_afpacenter_formation_formationsession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afpacenter',
            options={'verbose_name': 'Centre AFPA', 'verbose_name_plural': 'Centres AFPA'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Voiture', 'verbose_name_plural': 'Voitures'},
        ),
        migrations.AlterModelOptions(
            name='formation',
            options={'verbose_name': 'Formation', 'verbose_name_plural': 'Formations'},
        ),
        migrations.AlterModelOptions(
            name='formationsession',
            options={'verbose_name': 'Sessions de formation'},
        ),
        migrations.RemoveField(
            model_name='formationsession',
            name='afpa_center',
        ),
    ]
