# Generated by Django 2.0.6 on 2018-07-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covoiturage', '0008_auto_20180730_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_label',
            new_name='address_label_public',
        ),
    ]
