# Generated by Django 2.0.6 on 2018-07-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covoiturage', '0009_auto_20180730_1041'),
        ('covoiturage', '0009_auto_20180730_1657'),
    ]

    operations = [
    ]
